// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_add_state(ui_Screen1, LV_STATE_FOCUSED);       /// States
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Screen1, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_flex_flow(ui_Screen1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Screen1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_ContainerPageM1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_ContainerPageM1);
    lv_obj_set_width(ui_ContainerPageM1, 160);
    lv_obj_set_height(ui_ContainerPageM1, 80);
    lv_obj_set_align(ui_ContainerPageM1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerPageM1,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_ContainerPageM1, LV_SCROLLBAR_MODE_OFF);

    ui_Chart1 = lv_chart_create(ui_ContainerPageM1);
    lv_obj_set_width(ui_Chart1, 138);
    lv_obj_set_height(ui_Chart1, 71);
    lv_obj_set_x(ui_Chart1, 4);
    lv_obj_set_y(ui_Chart1, -5);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Chart1, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Chart1, 121);
    lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 0, 300);
    lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 0, 600);
    lv_chart_set_div_line_count(ui_Chart1, 7, 13);
    lv_chart_set_zoom_x(ui_Chart1, 255);
    lv_chart_set_zoom_y(ui_Chart1, 250);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 0, 0, 13, 1, true, 0);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 0, 0, 7, 1, true, 0);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 7, 1, true, 15);
    lv_obj_set_style_radius(ui_Chart1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Chart1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Chart1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Chart1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_Chart1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_rounded(ui_Chart1, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Chart1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Chart1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Chart1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Chart1, -1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_Chart1, 2, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Chart1, 2, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Chart1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Chart1, 2, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    lv_obj_set_style_line_width(ui_Chart1, 1, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_size(ui_Chart1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_line_width(ui_Chart1, 0, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Chart1, LV_TEXT_ALIGN_RIGHT, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Chart1, &ui_font_silver12, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_ButtonChartRestart = lv_btn_create(ui_ContainerPageM1);
    lv_obj_set_x(ui_ButtonChartRestart, 0);
    lv_obj_set_y(ui_ButtonChartRestart, -60);
    lv_obj_set_align(ui_ButtonChartRestart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonChartRestart, LV_OBJ_FLAG_FLOATING | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonChartRestart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonChartRestart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonChartRestart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerPage0 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_ContainerPage0);
    lv_obj_set_width(ui_ContainerPage0, 160);
    lv_obj_set_height(ui_ContainerPage0, 80);
    lv_obj_set_x(ui_ContainerPage0, 7);
    lv_obj_set_y(ui_ContainerPage0, -55);
    lv_obj_set_align(ui_ContainerPage0, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerPage0, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerPage0, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerPage0,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_ContainerPage0, LV_SCROLLBAR_MODE_OFF);

    ui_Container1c1 = lv_obj_create(ui_ContainerPage0);
    lv_obj_remove_style_all(ui_Container1c1);
    lv_obj_set_width(ui_Container1c1, 80);
    lv_obj_set_height(ui_Container1c1, 80);
    lv_obj_set_x(ui_Container1c1, -2);
    lv_obj_set_y(ui_Container1c1, -11);
    lv_obj_set_align(ui_Container1c1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1c1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container1c1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container1c1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Container1c1, LV_SCROLLBAR_MODE_OFF);

    ui_Container1c1c1 = lv_obj_create(ui_Container1c1);
    lv_obj_remove_style_all(ui_Container1c1c1);
    lv_obj_set_height(ui_Container1c1c1, 26);
    lv_obj_set_width(ui_Container1c1c1, lv_pct(100));
    lv_obj_set_x(ui_Container1c1c1, 200);
    lv_obj_set_y(ui_Container1c1c1, -66);
    lv_obj_set_align(ui_Container1c1c1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1c1c1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1c1c1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1c1c1,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Container1c1c1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_Container1c1c1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container1c1c1, lv_color_hex(0x2FB8D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1c1c1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRealVoltage = lv_label_create(ui_Container1c1c1);
    lv_obj_set_width(ui_LabelRealVoltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRealVoltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRealVoltage, -27);
    lv_obj_set_y(ui_LabelRealVoltage, -19);
    lv_obj_set_align(ui_LabelRealVoltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRealVoltage, "20.38V");
    lv_obj_clear_flag(ui_LabelRealVoltage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_LabelRealVoltage, &ui_font_NovaMono22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelRealVoltage, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelRealVoltage, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelRealVoltage, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelRealVoltage, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1c1c2 = lv_obj_create(ui_Container1c1);
    lv_obj_remove_style_all(ui_Container1c1c2);
    lv_obj_set_height(ui_Container1c1c2, 26);
    lv_obj_set_width(ui_Container1c1c2, lv_pct(100));
    lv_obj_set_x(ui_Container1c1c2, 5);
    lv_obj_set_y(ui_Container1c1c2, -2);
    lv_obj_set_align(ui_Container1c1c2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1c1c2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1c1c2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1c1c2,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Container1c1c2, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_Container1c1c2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container1c1c2, lv_color_hex(0x1AD1B2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1c1c2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRealCurrent = lv_label_create(ui_Container1c1c2);
    lv_obj_set_width(ui_LabelRealCurrent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRealCurrent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRealCurrent, -25);
    lv_obj_set_y(ui_LabelRealCurrent, -31);
    lv_obj_set_align(ui_LabelRealCurrent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRealCurrent, "5.799A");
    lv_obj_clear_flag(ui_LabelRealCurrent, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_LabelRealCurrent, &ui_font_NovaMono22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelRealCurrent, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelRealCurrent, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelRealCurrent, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelRealCurrent, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1c1c3 = lv_obj_create(ui_Container1c1);
    lv_obj_remove_style_all(ui_Container1c1c3);
    lv_obj_set_height(ui_Container1c1c3, 26);
    lv_obj_set_width(ui_Container1c1c3, lv_pct(100));
    lv_obj_set_x(ui_Container1c1c3, 5);
    lv_obj_set_y(ui_Container1c1c3, -18);
    lv_obj_set_align(ui_Container1c1c3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1c1c3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1c1c3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1c1c3,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Container1c1c3, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_Container1c1c3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container1c1c3, lv_color_hex(0xAACA4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1c1c3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRealPower = lv_label_create(ui_Container1c1c3);
    lv_obj_set_width(ui_LabelRealPower, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRealPower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRealPower, -27);
    lv_obj_set_y(ui_LabelRealPower, -19);
    lv_obj_set_align(ui_LabelRealPower, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRealPower, "10.99W");
    lv_obj_clear_flag(ui_LabelRealPower, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_LabelRealPower, &ui_font_NovaMono22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelRealPower, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelRealPower, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelRealPower, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelRealPower, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1c2 = lv_obj_create(ui_ContainerPage0);
    lv_obj_remove_style_all(ui_Container1c2);
    lv_obj_set_width(ui_Container1c2, 79);
    lv_obj_set_height(ui_Container1c2, 80);
    lv_obj_set_align(ui_Container1c2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1c2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container1c2, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1c2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Container1c2, LV_SCROLLBAR_MODE_OFF);

    ui_Container1c2c1 = lv_obj_create(ui_Container1c2);
    lv_obj_remove_style_all(ui_Container1c2c1);
    lv_obj_set_height(ui_Container1c2c1, 26);
    lv_obj_set_width(ui_Container1c2c1, lv_pct(100));
    lv_obj_set_align(ui_Container1c2c1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1c2c1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1c2c1, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1c2c1,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Container1c2c1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_Container1c2c1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container1c2c1, lv_color_hex(0xDDA54D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1c2c1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRealTemp = lv_label_create(ui_Container1c2c1);
    lv_obj_set_width(ui_LabelRealTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRealTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRealTemp, -27);
    lv_obj_set_y(ui_LabelRealTemp, -19);
    lv_obj_set_align(ui_LabelRealTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRealTemp, "0.555℃");
    lv_obj_set_style_text_font(ui_LabelRealTemp, &ui_font_NovaMono22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelRealTemp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelRealTemp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelRealTemp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelRealTemp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1c2c2 = lv_obj_create(ui_Container1c2);
    lv_obj_remove_style_all(ui_Container1c2c2);
    lv_obj_set_height(ui_Container1c2c2, 26);
    lv_obj_set_width(ui_Container1c2c2, lv_pct(100));
    lv_obj_set_align(ui_Container1c2c2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1c2c2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1c2c2, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1c2c2,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_radius(ui_Container1c2c2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container1c2c2, lv_color_hex(0x9F89EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1c2c2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRealDuty = lv_label_create(ui_Container1c2c2);
    lv_obj_set_width(ui_LabelRealDuty, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRealDuty, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRealDuty, -27);
    lv_obj_set_y(ui_LabelRealDuty, -19);
    lv_obj_set_align(ui_LabelRealDuty, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRealDuty, "100.0%");
    lv_obj_set_style_text_font(ui_LabelRealDuty, &ui_font_NovaMono22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelRealDuty, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelRealDuty, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelRealDuty, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelRealDuty, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1c2c3 = lv_obj_create(ui_Container1c2);
    lv_obj_remove_style_all(ui_Container1c2c3);
    lv_obj_set_height(ui_Container1c2c3, 26);
    lv_obj_set_width(ui_Container1c2c3, lv_pct(100));
    lv_obj_set_x(ui_Container1c2c3, -70);
    lv_obj_set_y(ui_Container1c2c3, 0);
    lv_obj_set_align(ui_Container1c2c3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1c2c3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1c2c3, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1c2c3,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Container1c2c3, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_Container1c2c3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Container1c2c3, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonHeatingToggle = lv_btn_create(ui_Container1c2c3);
    lv_obj_set_width(ui_ButtonHeatingToggle, lv_pct(100));
    lv_obj_set_height(ui_ButtonHeatingToggle, lv_pct(100));
    lv_obj_set_align(ui_ButtonHeatingToggle, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonHeatingToggle, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonHeatingToggle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonHeatingToggle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonHeatingToggle, 0, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUSED);

    ui_LabelHeatingToggle = lv_label_create(ui_ButtonHeatingToggle);
    lv_obj_set_width(ui_LabelHeatingToggle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHeatingToggle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelHeatingToggle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHeatingToggle, "START");
    lv_obj_set_style_text_font(ui_LabelHeatingToggle, &ui_font_NovaMono22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerPage1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_ContainerPage1);
    lv_obj_set_width(ui_ContainerPage1, 160);
    lv_obj_set_height(ui_ContainerPage1, 80);
    lv_obj_set_align(ui_ContainerPage1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerPage1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ContainerPage1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ContainerPage1,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_ContainerPage1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_ContainerPage1, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ContainerPage1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_ContainerPage1);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_height(ui_Container8, 15);
    lv_obj_set_width(ui_Container8, lv_pct(100));
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Label9, 30);
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "KP");
    lv_obj_set_style_text_align(ui_Label9, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &ui_font_silver20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSetKp = lv_slider_create(ui_Container8);
    lv_slider_set_range(ui_SliderSetKp, 0, 500);
    lv_slider_set_value(ui_SliderSetKp, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSetKp) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderSetKp, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSetKp, 80);
    lv_obj_set_height(ui_SliderSetKp, 4);
    lv_obj_set_align(ui_SliderSetKp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SliderSetKp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_pad_left(ui_SliderSetKp, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderSetKp, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderSetKp, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderSetKp, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelSetKp = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_LabelSetKp, 35);
    lv_obj_set_height(ui_LabelSetKp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSetKp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSetKp, "0");
    lv_obj_set_style_text_align(ui_LabelSetKp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSetKp, &ui_font_silver20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelSetKp, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelSetKp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelSetKp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelSetKp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container9 = lv_obj_create(ui_ContainerPage1);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_height(ui_Container9, 15);
    lv_obj_set_width(ui_Container9, lv_pct(100));
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_Label10, 30);
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "KI");
    lv_obj_set_style_text_align(ui_Label10, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_silver20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSetKi = lv_slider_create(ui_Container9);
    lv_slider_set_range(ui_SliderSetKi, 0, 500);
    lv_slider_set_value(ui_SliderSetKi, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSetKi) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderSetKi, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSetKi, 80);
    lv_obj_set_height(ui_SliderSetKi, 4);
    lv_obj_set_align(ui_SliderSetKi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SliderSetKi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_pad_left(ui_SliderSetKi, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderSetKi, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderSetKi, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderSetKi, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelSetKi = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_LabelSetKi, 35);
    lv_obj_set_height(ui_LabelSetKi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSetKi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSetKi, "0");
    lv_obj_set_style_text_align(ui_LabelSetKi, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSetKi, &ui_font_silver20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelSetKi, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelSetKi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelSetKi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelSetKi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container10 = lv_obj_create(ui_ContainerPage1);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_height(ui_Container10, 15);
    lv_obj_set_width(ui_Container10, lv_pct(100));
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container10, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_Label11, 30);
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "KD");
    lv_obj_set_style_text_align(ui_Label11, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &ui_font_silver20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSetKd = lv_slider_create(ui_Container10);
    lv_slider_set_range(ui_SliderSetKd, 0, 500);
    lv_slider_set_value(ui_SliderSetKd, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSetKd) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderSetKd, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSetKd, 80);
    lv_obj_set_height(ui_SliderSetKd, 4);
    lv_obj_set_align(ui_SliderSetKd, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SliderSetKd, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_pad_left(ui_SliderSetKd, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderSetKd, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderSetKd, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderSetKd, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelSetKd = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_LabelSetKd, 35);
    lv_obj_set_height(ui_LabelSetKd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSetKd, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSetKd, "0");
    lv_obj_set_style_text_align(ui_LabelSetKd, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSetKd, &ui_font_silver20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelSetKd, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelSetKd, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelSetKd, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelSetKd, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDebug = lv_label_create(ui_ContainerPage1);
    lv_obj_set_width(ui_LabelDebug, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDebug, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDebug, 0);
    lv_obj_set_y(ui_LabelDebug, 30);
    lv_obj_set_align(ui_LabelDebug, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDebug, "DEBUG");
    lv_obj_add_flag(ui_LabelDebug, LV_OBJ_FLAG_FLOATING | LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_obj_clear_flag(ui_LabelDebug, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_LabelDebug, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDebug, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDebug, &ui_font_silver12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelDebug, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelDebug, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelDebug, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelDebug, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelDebug, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelDebug, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelDebug, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerPage2 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_ContainerPage2);
    lv_obj_set_width(ui_ContainerPage2, 160);
    lv_obj_set_height(ui_ContainerPage2, 80);
    lv_obj_set_align(ui_ContainerPage2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerPage2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ContainerPage2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ContainerPage2,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_ContainerPage2, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_ContainerPage2, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ContainerPage2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container11 = lv_obj_create(ui_ContainerPage2);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_height(ui_Container11, 15);
    lv_obj_set_width(ui_Container11, lv_pct(100));
    lv_obj_set_align(ui_Container11, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container11, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container11, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_Label17, 30);
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "TEMP");
    lv_obj_set_style_text_font(ui_Label17, &ui_font_silver20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSetTemp = lv_slider_create(ui_Container11);
    lv_slider_set_range(ui_SliderSetTemp, 0, 250);
    lv_slider_set_value(ui_SliderSetTemp, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSetTemp) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderSetTemp, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSetTemp, 80);
    lv_obj_set_height(ui_SliderSetTemp, 4);
    lv_obj_set_align(ui_SliderSetTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SliderSetTemp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_pad_left(ui_SliderSetTemp, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderSetTemp, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderSetTemp, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderSetTemp, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelSetTemp = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_LabelSetTemp, 35);
    lv_obj_set_height(ui_LabelSetTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSetTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSetTemp, "200℃");
    lv_obj_set_style_text_align(ui_LabelSetTemp, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSetTemp, &ui_font_silver20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelSetTemp, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelSetTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelSetTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelSetTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_ContainerPage2);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_height(ui_Container2, 15);
    lv_obj_set_width(ui_Container2, lv_pct(100));
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label3, 30);
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "POWER");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_silver20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSetMaxPower = lv_slider_create(ui_Container2);
    lv_slider_set_range(ui_SliderSetMaxPower, 1, 250);
    lv_slider_set_value(ui_SliderSetMaxPower, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSetMaxPower) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderSetMaxPower, 0,
                                                                                                      LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSetMaxPower, 80);
    lv_obj_set_height(ui_SliderSetMaxPower, 4);
    lv_obj_set_align(ui_SliderSetMaxPower, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SliderSetMaxPower, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_pad_left(ui_SliderSetMaxPower, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderSetMaxPower, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderSetMaxPower, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderSetMaxPower, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelSetMaxPower = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_LabelSetMaxPower, 35);
    lv_obj_set_height(ui_LabelSetMaxPower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSetMaxPower, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSetMaxPower, "65W");
    lv_obj_set_style_text_font(ui_LabelSetMaxPower, &ui_font_silver20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelSetMaxPower, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelSetMaxPower, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelSetMaxPower, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelSetMaxPower, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_ContainerPage2);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_height(ui_Container3, 15);
    lv_obj_set_width(ui_Container3, lv_pct(100));
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label4, 30);
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "R-PCB");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_silver20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSetRPcb = lv_slider_create(ui_Container3);
    lv_slider_set_range(ui_SliderSetRPcb, 100, 1000);
    lv_slider_set_value(ui_SliderSetRPcb, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSetRPcb) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderSetRPcb, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSetRPcb, 80);
    lv_obj_set_height(ui_SliderSetRPcb, 4);
    lv_obj_set_align(ui_SliderSetRPcb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SliderSetRPcb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_pad_left(ui_SliderSetRPcb, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderSetRPcb, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderSetRPcb, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderSetRPcb, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelSetRPcb = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_LabelSetRPcb, 35);
    lv_obj_set_height(ui_LabelSetRPcb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSetRPcb, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSetRPcb, "3.75R");
    lv_obj_set_style_text_font(ui_LabelSetRPcb, &ui_font_silver20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelSetRPcb, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelSetRPcb, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelSetRPcb, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelSetRPcb, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_ContainerPage2);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_height(ui_Container1, 15);
    lv_obj_set_width(ui_Container1, lv_pct(100));
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label2, 30);
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "R-DIV");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_silver20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSetRDiv = lv_slider_create(ui_Container1);
    lv_slider_set_range(ui_SliderSetRDiv, 2000, 10000);
    lv_slider_set_mode(ui_SliderSetRDiv, LV_SLIDER_MODE_SYMMETRICAL);
    lv_slider_set_value(ui_SliderSetRDiv, 3000, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSetRDiv) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderSetRDiv, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSetRDiv, 80);
    lv_obj_set_height(ui_SliderSetRDiv, 4);
    lv_obj_set_align(ui_SliderSetRDiv, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SliderSetRDiv, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_pad_left(ui_SliderSetRDiv, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderSetRDiv, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderSetRDiv, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderSetRDiv, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelSetRDiv = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_LabelSetRDiv, 35);
    lv_obj_set_height(ui_LabelSetRDiv, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSetRDiv, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSetRDiv, "5100R");
    lv_obj_add_flag(ui_LabelSetRDiv, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_set_style_text_align(ui_LabelSetRDiv, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSetRDiv, &ui_font_silver20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelSetRDiv, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelSetRDiv, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelSetRDiv, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelSetRDiv, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_ContainerPage2);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_height(ui_Container6, 15);
    lv_obj_set_width(ui_Container6, lv_pct(100));
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label7, 30);
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "ADC");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_silver20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSetADCOffset = lv_slider_create(ui_Container6);
    lv_slider_set_range(ui_SliderSetADCOffset, -20, 20);
    lv_slider_set_mode(ui_SliderSetADCOffset, LV_SLIDER_MODE_SYMMETRICAL);
    lv_slider_set_value(ui_SliderSetADCOffset, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSetADCOffset) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderSetADCOffset, 0,
                                                                                                       LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSetADCOffset, 80);
    lv_obj_set_height(ui_SliderSetADCOffset, 4);
    lv_obj_set_align(ui_SliderSetADCOffset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SliderSetADCOffset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_pad_left(ui_SliderSetADCOffset, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderSetADCOffset, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderSetADCOffset, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderSetADCOffset, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelSetADCOffset = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_LabelSetADCOffset, 35);
    lv_obj_set_height(ui_LabelSetADCOffset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSetADCOffset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSetADCOffset, "0mV");
    lv_obj_add_flag(ui_LabelSetADCOffset, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_set_style_text_align(ui_LabelSetADCOffset, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSetADCOffset, &ui_font_silver20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelSetADCOffset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelSetADCOffset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelSetADCOffset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelSetADCOffset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerPage3 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_ContainerPage3);
    lv_obj_set_width(ui_ContainerPage3, 160);
    lv_obj_set_height(ui_ContainerPage3, 80);
    lv_obj_set_align(ui_ContainerPage3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerPage3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ContainerPage3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ContainerPage3,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_ContainerPage3, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_ContainerPage3, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ContainerPage3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container16 = lv_obj_create(ui_ContainerPage3);
    lv_obj_remove_style_all(ui_Container16);
    lv_obj_set_height(ui_Container16, 15);
    lv_obj_set_width(ui_Container16, lv_pct(100));
    lv_obj_set_align(ui_Container16, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container16, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container16, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags

    ui_Label1 = lv_label_create(ui_Container16);
    lv_obj_set_width(ui_Label1, 30);
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "BL");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_silver20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSetBL = lv_slider_create(ui_Container16);
    lv_slider_set_range(ui_SliderSetBL, 1, 100);
    lv_slider_set_value(ui_SliderSetBL, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSetBL) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderSetBL, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSetBL, 80);
    lv_obj_set_height(ui_SliderSetBL, 4);
    lv_obj_set_align(ui_SliderSetBL, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SliderSetBL, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_pad_left(ui_SliderSetBL, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderSetBL, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderSetBL, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderSetBL, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelSetBL = lv_label_create(ui_Container16);
    lv_obj_set_width(ui_LabelSetBL, 35);
    lv_obj_set_height(ui_LabelSetBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSetBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSetBL, "100%");
    lv_obj_set_style_text_align(ui_LabelSetBL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSetBL, &ui_font_silver20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelSetBL, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelSetBL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelSetBL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelSetBL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_ContainerPage3);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_height(ui_Container4, 15);
    lv_obj_set_width(ui_Container4, lv_pct(100));
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags

    ui_Label5 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label5, 30);
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "VOL");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_silver20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSetVol = lv_slider_create(ui_Container4);
    lv_slider_set_value(ui_SliderSetVol, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSetVol) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderSetVol, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSetVol, 80);
    lv_obj_set_height(ui_SliderSetVol, 4);
    lv_obj_set_align(ui_SliderSetVol, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SliderSetVol, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_pad_left(ui_SliderSetVol, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderSetVol, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderSetVol, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderSetVol, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelSetVol = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_LabelSetVol, 35);
    lv_obj_set_height(ui_LabelSetVol, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSetVol, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSetVol, "100%");
    lv_obj_set_style_text_align(ui_LabelSetVol, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSetVol, &ui_font_silver20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelSetVol, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelSetVol, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelSetVol, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelSetVol, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_ContainerPage3);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_height(ui_Container5, 15);
    lv_obj_set_width(ui_Container5, lv_pct(100));
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags

    ui_Label6 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label6, 30);
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "NOTE");
    lv_obj_set_style_text_font(ui_Label6, &ui_font_silver20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSetNote = lv_slider_create(ui_Container5);
    lv_slider_set_range(ui_SliderSetNote, 20, 88);
    lv_slider_set_value(ui_SliderSetNote, 88, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSetNote) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderSetNote, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSetNote, 80);
    lv_obj_set_height(ui_SliderSetNote, 4);
    lv_obj_set_align(ui_SliderSetNote, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SliderSetNote, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_pad_left(ui_SliderSetNote, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderSetNote, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderSetNote, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderSetNote, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelSetNote = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_LabelSetNote, 35);
    lv_obj_set_height(ui_LabelSetNote, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSetNote, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSetNote, "88");
    lv_obj_set_style_text_align(ui_LabelSetNote, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSetNote, &ui_font_silver20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelSetNote, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelSetNote, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelSetNote, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelSetNote, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerPage4 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_ContainerPage4);
    lv_obj_set_width(ui_ContainerPage4, 160);
    lv_obj_set_height(ui_ContainerPage4, 80);
    lv_obj_set_x(ui_ContainerPage4, -63);
    lv_obj_set_y(ui_ContainerPage4, 5);
    lv_obj_set_align(ui_ContainerPage4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerPage4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerPage4, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerPage4,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_ContainerPage4, LV_SCROLLBAR_MODE_OFF);

    ui_Roller1 = lv_roller_create(ui_ContainerPage4);
    lv_roller_set_options(ui_Roller1, "5V\n9V\n12V\n15V\n18V\n20V", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Roller1, 55);
    lv_obj_set_height(ui_Roller1, 55);
    lv_obj_set_x(ui_Roller1, 252);
    lv_obj_set_y(ui_Roller1, -5);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Roller1, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Roller1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Roller1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roller1, &ui_font_silver20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Roller1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Roller1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Roller1, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_width(ui_Roller1, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_pad(ui_Roller1, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_Roller1, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_Roller1, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_Roller1, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_Roller1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_Roller1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_Roller1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_set_style_radius(ui_Roller1, 10, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_ContainerPage5 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_ContainerPage5);
    lv_obj_set_width(ui_ContainerPage5, 160);
    lv_obj_set_height(ui_ContainerPage5, 80);
    lv_obj_set_x(ui_ContainerPage5, 7);
    lv_obj_set_y(ui_ContainerPage5, -55);
    lv_obj_set_align(ui_ContainerPage5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerPage5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerPage5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerPage5,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_ContainerPage5, LV_SCROLLBAR_MODE_OFF);

    ui_Panel1 = lv_obj_create(ui_ContainerPage5);
    lv_obj_set_width(ui_Panel1, lv_pct(95));
    lv_obj_set_height(ui_Panel1, lv_pct(90));
    lv_obj_set_x(ui_Panel1, -275);
    lv_obj_set_y(ui_Panel1, -402);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLL_ELASTIC);      /// Flags
    lv_obj_set_scroll_dir(ui_Panel1, LV_DIR_VER);
    lv_obj_set_style_radius(ui_Panel1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_Panel1, 100, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_FOCUSED);

    ui_LabelPDInfo = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_LabelPDInfo, lv_pct(100));
    lv_obj_set_height(ui_LabelPDInfo, LV_SIZE_CONTENT);    /// 100
    lv_label_set_text(ui_LabelPDInfo, "PD INFO");
    lv_obj_add_flag(ui_LabelPDInfo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_clear_flag(ui_LabelPDInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_LabelPDInfo, LV_DIR_VER);
    lv_obj_set_style_text_color(ui_LabelPDInfo, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPDInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPDInfo, &ui_font_silver20, LV_PART_MAIN | LV_STATE_DEFAULT);


}
